// <auto-generated />
namespace EfRipositpry.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _02addBodPersionfildtouserentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02addBodPersionfildtouserentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201905060913112_02-add-BodPersion-fild-to-user-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
